name: deploy-to-firebase-ionic-app

on:
  push:
    branches: 
      - master

jobs:
  deploy-to-firebase-hosting:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1.0.0
        
        # we have to install app-scripts
      - run: npm i -D -E @ionic/app-scripts
      
      - name: build ionic
        run: |
          ionic build
            
      - name: selec firebase proyect
        uses: w9jds/firebase-action@master
        with:
          args: projects:list
        env:
          FIREBASE_TOKEN: 1//05lBAkod8AzWICgYIARAAGAUSNwF-L9IraThjLApNW7pGceLXhfkhZt9NYSfL7TSMk7ocYRxbXDLEneiwv4_r_NJf4RQT02SFmqc
          
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//05lBAkod8AzWICgYIARAAGAUSNwF-L9IraThjLApNW7pGceLXhfkhZt9NYSfL7TSMk7ocYRxbXDLEneiwv4_r_NJf4RQT02SFmqc
